### ISSUE TITLE
Issue in Closing NvArgusCamera Pipeline

### ISSUE THREAD

**Issue by yashrajsapra** [Apra-Labs/ApraPipes#109]
**Describe the bug**
While Closing a pipeline with NvaArgusCamera Source, it stuck inside the wait_for_all function (inside joining thread)

**To Reproduce**
1.  Have a Pipeline with NvArgusCamera Source along with a sink
2. And try to close the pipeline after 10 sec
3. It will be stuck until someone forcefully kills the pipeline 

**Expected behavior**
Pipeline should close after wait_for_all

**Comment by kumaakh** [comment]
Thanks Yashraj,

Do you have a fix for this issue?

**Comment by yashrajsapra** [comment]
Ya, I have a fix for that,
I will create a PR and maybe you can review the code

**Comment by kumaakh** [comment]
sounds good
-Akhil
https://www.linkedin.com/in/akhilk
Ph: +91 9845495104
