### ISSUE TITLE
Enhance pipeline to have flush all queues functionality

### ISSUE THREAD

**Issue by mraduldubey** [Apra-Labs/ApraPipes#128]
**Is your feature request related to a problem? Please describe.**
`flushQueRecursive` flushes the queues for the the module and all its descendants. It only makes sense to have a pipeline based API for flushing all the queues in the whole pipeline. Currently, we will have to call flush pipeline for all the source modules manually in case of multiple source modules.

**Describe the solution you'd like**
`PipeLine` will have a `flush_all_queues` method to call `flushQueRecursive` for all the source modules.

**Describe alternatives you've considered**
None

**Comment by kumaakh** [comment]
fixed in #126

**Comment by mraduldubey** [comment]
Assigning to venkat
