### ISSUE TITLE
InvalidState error

### ISSUE THREAD

**Issue by varmakvl7** [Apra-Labs/ApraPipes#14]
Getting WARNING from ARGUS saying that 
![h264encoderv4l2_tests-yuv420_640x360](https://user-images.githubusercontent.com/77491235/107022519-873ee480-67cb-11eb-8ea4-445271ebb501.png)
20 client objects still exist during shutdown

**Comment by mraduldubey** [comment]
Update status @yashrajsapra @varmakvl7

**Comment by yashrajsapra** [comment]
Fixed in #66[https://github.com/Apra-Labs/ApraPipes/pull/63]
