### ISSUE TITLE
Bug in Nvtransform module

### ISSUE THREAD

**Issue by yashrajsapra** [Apra-Labs/ApraPipes#144]
**Describe the bug**
NvTransform module should do crop ,color conversion and scale but it actually doing only color transform and scale

**To Reproduce**
1. Pass width and height to crop
**Expected behavior**
It should crop from the frame but it's not doing that

**Comment by kumaakh** [comment]
why is this closed ?

**Comment by yashrajsapra** [comment]
Testes it on latest version of ApraPipes it worked fine.

Will raise one feature related ticket to improve nvtransform module to have
crop , scale, and color transform as a independent feature.

**Comment by yashrajsapra** [comment]
Tested it with the latest version of Aprapipes, and all tests passed
successfully

I will raise a separate ticket for the improvement that we discussed on
nvtransform module.

->  Adding separate strategies for a crop, rescale, and color transform
->  Adding extra Constructor for color transform
