### ISSUE TITLE
Module for maintaining diskspace

### ISSUE THREAD

**Issue by kumaakh** [Apra-Labs/ApraPipes#162]
**Is your feature request related to a problem? Please describe.**
typical NVR applications are expected to watch the available disk space and make sure that the NVR does not crash due to disk space full errors hence it is important to have a module which can watch the archieve 's disk utilization

**Describe the solution you'd like**
A module which is able to watch the disk space and clean old files. Following simple props apply

1. Path: the pathe to watch (e.g. /var/nvr/cam1)
2. upper_water_mark: space in MB (e.g. 900MB) which triggers a corrective actions (e.g. deletion)
3. lower_water_mark:  space in MB (e.g. 750MB) which the a corrective action aspires to acheive 
4. a pattern for file name which can be deleted to acheive the move from high_water_mark to lower_water_mark (e.g. *.mp4)

**Describe alternatives you've considered**
there is linux utility named "tmpreaper" that can be considered here

**Additional context**

we should try to avoid making too many filesystem queries in learning the current state... a good approach can be as follows

- At a very low frequency we do a fine analysis, while at a higher (but still low) frequency we do coarser analysis
- fine analysis => we know files sizes of each and every file
- coarse analysis => just count the additional files and project based on some averaging scheme (average size of latest 10 files can be used to predict the size of next 10 files)
- goal is to defer the fine analysis as mush as possible

**Additionally** strive to avoid disk full situation (other than the high and low water mark)
e.g. if the high watermark is misconfigured to be more than available disk space... we should try to avoid making diskful and go to lower water mark

**Comment by mraduldubey** [comment]
Should we take multiple patterns as props ?

**Comment by yashrajsapra** [comment]
We can additionally use other strategies like:-
1. Moving archive
2. Compressing archive (in case of raw or other formats which can be further compressed)
3. Moving & Compressing
