### ISSUE TITLE
Bugs in fix-vcpkg-json.sh

### ISSUE THREAD

**Issue by mraduldubey** [Apra-Labs/ApraPipes#219]
**Describe the bug**
The fix-vcpkg-json.sh has multiple bugs

**To Reproduce**
Try to run the script and observe the modified vcpkg.json 

**Expected behavior**
All options (removeCuda| removeOpenCV | onlyOpenCV) should work correctly
- removeCuda - no cuda build + opencv
- removeOpenCV - remove opencv from original vcpkg.json
- onlyOpenCV - no cuda build + only dependency is opencv

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: any
 - Architecture x86_64, arm64

**Additional context**
Need to have a bash script that is equivalent of `base\fix-vcpkg-json.ps1`

**Comment by mraduldubey** [comment]
@kumaakh Please check if the options are defined correctly above.

**Comment by venkat0907** [comment]
i was unable to reproduce the issue

**Comment by mraduldubey** [comment]
Lets verify this once more by writing a program that prints input vcpkg.json and modified output.

**Comment by mraduldubey** [comment]
Venkat verified but we could not replicate the issue. So, closing this.
