### ISSUE TITLE
Listing Mp4 UT Issues

### ISSUE THREAD

**Issue by mraduldubey** [Apra-Labs/ApraPipes#229]
**Describe the bug**
Improve the existing UTs for Mp4ReaderSource

**To Reproduce**
Check mp4readersource_tests.cpp

**Expected behavior**
1. Rewrite the UTs using save or compare 
2. Rewrite getSetProps test to actually test something
3. Add a test for metadata verification (have a video with alternating metadata) - verify in sink
4. Remove seek tests. All Seek tests should be put in mp4_seek_tests
5. In UT of mp4reader - not required modules should be present in the pipeline. Currently, extra modules are present
6. Add some tests for correct metadata of a frame after random seek is done
7. None of the test should be providing the resolution of the video to the mp4 reader - because it reads resolution on its own

**Screenshots**

**Desktop (please complete the following information):**
 - OS: All
 - Cuda Version: N/A
 - Architecture: All

**Would you like to work on the issue?**
@mohammedzakikochargi

**Comment by mraduldubey** [comment]
More comments about Mp4 UTs:

1. None of the test should be providing the resolution of the video to the mp4 reader - because it reads resolution on its own

**Comment by mraduldubey** [comment]
@mohammedzakikochargi have we addressed all these comments

**Comment by mohammedzakikochargi** [comment]
> @mohammedzakikochargi have we addressed all these comments

Yes.
