### ISSUE TITLE
H264Decoder module not terminating

### ISSUE THREAD

**Issue by yashrajsapra** [Apra-Labs/ApraPipes#251]
**Describe the bug**
While closing the pipeline we found out that H264Decoder module is stuck in a thread joining phase, As there are 2 unclosed while loop which is running 
**To Reproduce**
1. Add module "Camera Source -> Decoder " to the pipeline
2. Run pipeline 

**Expected behavior**
The pipeline should end when we terminate pipeline

**Comment by kumaakh** [comment]
@mraduldubey @mohammedzakikochargi  this is an important issue to fix
