### ISSUE TITLE
check fileReader->init() has failed

### ISSUE THREAD

**Issue by AkshayPS12** [Apra-Labs/ApraPipes#28]
While running apra pipes UTs FileReader module throws error.
`/home/ubuntu/src/ApraPipes/base/test/nvjpeg_combo_tests.cpp(116): error: in "nvjpeg_combo_tests/decode_resize_cc_raw_1920x960": check fileReader->init() has failed`

**Comment by kumaakh** [comment]
@Vinayak-YB please work on this issue
