### ISSUE TITLE
Mp4Writer frame data update issue.

### ISSUE THREAD

**Issue by mohammedzakikochargi** [Apra-Labs/ApraPipes#302]
**Describe the bug**
In the Mp4writer, for h264 strategy we are updating the h264 frame->data() to make video playback compatible on all video players.
As in we change the nalu separators format as per Mp4 format. 
If the source is connected to multiple modules and Mp4Writer then same frame_sp is passed to multiple modules and Mp4Writer , Now as we change the frame_sp->data() in Mp4writer the updated frame_sp->data() is being sent to other modules connected to the same source and hence causing issues, specifically in H264Decoder wherein h264 data needs to be in annex B format.

**To Reproduce**
Create a pipeline :
Connect a single rtsp source module to MultiMediaQueue , Mp4Writer and H264decoder.

**Expected behavior**
In the Above pipeline the same frame_sp being used in Mp4Writer should be able to be decoded in H264Decoder module

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. chrome, safari]
 - Cuda Version [e.g. 22]
 - Architecture [e.g. x86_64, arm64]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by kumaakh** [comment]
The buffer should not be changed but instead, while writing an incremented pointer and reduced length should be passed.

**Comment by yashrajsapra** [comment]
Reopening the issue, because it's not handled for JPEG strategy
