### ISSUE TITLE
Set Thread Name

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [Apra-Labs/ApraPipes#35]
Setting Thread Name helps in debugging core dumps

**Comment by mraduldubey** [comment]
Assigned to @Vinayak-YB

**Comment by kumaakh** [comment]
currently each module runs as a thread, each module has a name, we should set the threadname to be same as module name. this way when we recieve a crashdump we can know which thread is which. Lookup boost threads to see API for setting the threadname.
