### ISSUE TITLE
Affine Transform Module

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [Apra-Labs/ApraPipes#36]
Input is a Raw Image (Mono, YUV or RGB) 
Output is also a Raw Image (Mono, YUV or RGB) 

Affine matrix is provided as a dynamic property: 
https://docs.opencv.org/3.4.15/d4/d61/tutorial_warp_affine.html

We should try support at least two Interpolation methods: Bilinear: (INTER_LINEAR in openCV) and BiCubic: (INTER_CUBIC in OpenCV)

**Comment by yashrajsapra** [comment]
Affine Transform  Module currently supports only DMA memory.

**Comment by yashrajsapra** [comment]
Will improve this module to work on CPU and GPU

**Comment by joiskash** [comment]
@kumaakh so currently modules are separated as either DMA/GPU support or CPU support. So in this module @yashrajsapra will only be supporting DMA and GPU. We will create another affine transform module for CPU. 
Please let us know your thoughts

**Comment by kumaakh** [comment]
Ideally we should think of this as a feature of the module. The same module
should be enhanced to support CPU or other memory modules based on input
pin type

**Comment by joiskash** [comment]
So should enhancement be another task and PR?

**Comment by kumaakh** [comment]
Yes it's fine to enhance in the next PR. focus should be on code reuse.

-Akhil
https://www.linkedin.com/in/akhilk
Ph: +91 9845495104

**Comment by mraduldubey** [comment]
@akhil-ku Yash tells me that NPP based Affine Transformation can be added to this module. Should we take this on ? Want to assign it to @venkat0907
