### ISSUE TITLE
Thirdparty libraries should not be built inside the same folder

### ISSUE THREAD

**Issue by kumaakh** [Apra-Labs/ApraPipes#42]
**Is your feature request related to a problem? Please describe.**
It is a bad idea to build anything inside the same folder where the source code lives. 
I am trying to implement caching in CI build. as-is the build output is currently interleved with the sourec code so my only choice at this point is to cache the whole folder

**Describe the solution you'd like**
The output of ffmpeg and zxing builds should go into thirdparty/_build or similar folders

**Describe alternatives you've considered**
pushing the whole folder to cache (source+binaries)

**Comment by joiskash** [comment]
Done #246
