### ISSUE TITLE
Migrate to vcpkg package manager

### ISSUE THREAD

**Issue by kumaakh** [Apra-Labs/ApraPipes#48]
Currently we use hunter and in last 4-5 yrs we have realized that while hunter is great, it is not for the faint at heart.  A competing package manager https://github.com/microsoft/vcpkg is gaining popularity and it has ~1800 packages already. We should make an attempt to migrate us to vcpkg ASAP

**Comment by joiskash** [comment]
Successfully built on windows x 64 - no cuda, dynamic lib without QR reader , Virtual camera sink and Key Listener module. 
Open CV GTK tests failed.

**Comment by kumaakh** [comment]
Does zxing not exist in vcpkg ?

**Comment by joiskash** [comment]
The version that is there is very old. I have updated it to the new repo by nubook. I have also raised a draft pr in vcpkg.
