### ISSUE TITLE
Need Module to convert CPU to DMA copy

### ISSUE THREAD

**Issue by kumaakh** [Apra-Labs/ApraPipes#55]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. It would be nice to support [...] device

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kumaakh** [comment]
@shanbhagm please add more details here

**Comment by joiskash** [comment]
Done #283
