### ISSUE TITLE
Standardize naming convention for new modules

### ISSUE THREAD

**Issue by joiskash** [Apra-Labs/ApraPipes#64]
**Is your feature request related to a problem? Please describe.**
Document a standardized way of naming modules. 

**Describe the solution you'd like**

- Source Modules => S_SourceName_Platform eg: S_NVARGUS, S_AudioRecord
- Transform Modules => T_Transformation_Library eg: T_Affine_NPPI ,T_Rotate_CV
- Sink Modules => R_Renderer_Platform eg: R_CV, R_NVEGL 

**Describe alternatives you've considered**
None, the purpose is to have names that are intuitive. If no platform is specified then it is assumed to run for all platforms.

**Comment by kumaakh** [comment]
To be More Intuittive let's name as follows
[Name][Src/Xform/Sink]{_OptionalPlatform} e.g. 
AudioRecordSrc
AffineXform_NPPI 
etc. 
Also a platform variant should be created in very rare scenario. As far as possible we should try to consolidate all platform variants into a singke Module, offer a common interface, learn the users intentions via input/output pins or have explicit option about which variant to use.

**Comment by joiskash** [comment]
Lets move this to the wiki . Will create a contributing guidelines page

**Comment by joiskash** [comment]
https://github.com/Apra-Labs/ApraPipes/wiki/Contribution-Guidelines Has been updated with this information
