### ISSUE TITLE
Pinned versions of 3rd party packages

### ISSUE THREAD

**Issue by kumaakh** [Apra-Labs/ApraPipes#65]
current approach of vcpkg is pulling latest versions of every 3rd party software we use. this may not be good in a long run. it is better that we start using specific versions of 3rd party software, else we would see subtle unknown bugs on the fly.

I just realzied that the boost has moved to some newer version and now we are getting  the following warning which was not there earlier:

` note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.`

**Comment by joiskash** [comment]
We will be using the fork of vcpkg that is in Aprapipes to make sure we are in control of the versions. Apart from that we can also pin version using vcpkg https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/
