### ISSUE TITLE
 memory access violation

### ISSUE THREAD

**Issue by varmakvl7** [Apra-Labs/ApraPipes#7]
h264encoderv4l2helper_tests/yuv420_black is crashing when running all test cases but works fine when we run this single testcase.

**Comment by yashrajsapra** [comment]
Not able to reproduce, Test passed successfully 
![image](https://user-images.githubusercontent.com/88146397/192251511-8415e7e7-6067-4a5b-aee1-dfa1b55f9fec.png)
