### ISSUE TITLE
clear the litter generated by Audio Src test

### ISSUE THREAD

**Issue by kumaakh** [Apra-Labs/ApraPipes#77]
OK one comment which we can do it as an improvement after this merge, **the tests should always clear any litter generated...** e.g.  Audiotest*.wav files generated here will be left in the developers workspace and sometimes the test will be fooled because of the litter. e.g. file writing fails but a past copy of file exists in the same workspace. 

The solution is to add a destructor to the test  ~sound_record_tests() which deletes the files in a tolerant fashion so that if the file does not exit it does not crash and move to the next file.

_Originally posted by @kumaakh in https://github.com/Apra-Labs/ApraPipes/pull/62#r803097720_

**Comment by kumaakh** [comment]
@mansirthd could u please take up this task

**Comment by mraduldubey** [comment]
Assigning to @Vinayak-YB
